version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:rolling

    steps:
      - checkout

      - run:
          name: Installing GCC and CMake
          command: "apt-get update ; apt-get install -qy \
            gcc \
            g++ \
            make \
            cmake"

      - run:
          name: Installing Libosmium Dependencies
          command: "apt-get install -qy \
            git \
            doxygen \
            graphviz \
            libboost-dev \
            libprotozero-dev \
            libbz2-dev \
            libexpat1-dev \
            libgdal-dev \
            libgeos++-dev \
            libproj-dev \
            libsparsehash-dev \
            ruby \
            ruby-json \
            spatialite-bin \
            zlib1g-dev"
      - run:
          name: Downloading Libosmium
          command: "git clone https://github.com/osmcode/libosmium"
      - run:
          name: Creating Libosmium Build Files
          command: "cd libosmium ; mkdir build ; cd build ; cmake .."
      - run:
          name: Installing Libosmium
          command: "cd libosmium/build ; make install"

      - run:
          name: Creating Build Files
          command: "mkdir build ; cd build ; cmake .."
      - run:
          name: Compiling
          command: "cd build ; make"

      - run:
          name: Launching
          command: "cd build ; ./graphs"

workflows:
  version: 2.1
  main:
    jobs:
      - build
